### PR TITLE
Update to latest

### PR DESCRIPTION
**Pull request by kamilkisiela**
@schickling @marktani Thanks for the meetup ;)

### CODE REVIEW

**Comment by marktani** [comment]
hm todos are not showed, but I can create new todos on the server. do you see the same behaviour?

**Comment by marktani** [comment]
angular-todo

**Comment by kamilkisiela** [comment]
Need to catch up with few things, then I'll look at it :)

**Comment by kamilkisiela** [comment]
> hm todos are not shown even though allTodoes gets all todos from the server

Should be fixed in ab734cb

> adding new todos works, but they are not shown either

There's no mechanism to do this. There's no polling, no query updating etc.

**Pull request merged**
