### PR TITLE
First

### PR DESCRIPTION
**Pull request by kamilkisiela**
`angular2-apollo` + TypeScript

- [x] apollostack/angular2-apollo#34 to be merged and released (soon)

### CODE REVIEW

**Comment by schickling** [comment]
Wow! Thanks so much for this great PR @kamilkisiela!

I've just checkout this PR and would suggest the following changes:
- Add `typescript` as dev dependency
- Fix item padding as in screenshot below
screen shot 2016-06-25 at 17 05 24

**Comment by kamilkisiela** [comment]
Oh, I thought I already fixed that issue with padding but apparently it
didn't happen. I'll be able to work on it on Tuesday, maybe Wednesday :)

sob., 25 cze 2016, 17:06 użytkownik Johannes Schickling <
notifications@github.com> napisał:

**Comment by kamilkisiela** [comment]
I added the `ReversePipe` to load todos in reverse order (newest first). I also fixed that issue with padding but it's a little "hacky", hate working on css and I'm in the middle of the travel right now... :)

**Comment by schickling** [comment]
Awesome! Please ping here again once the Apollo issue has been resolved @kamilkisiela :)

**Comment by kamilkisiela** [comment]
@schickling :white_check_mark:

**Pull request merged**
